twig:
    paths:
        '%kernel.project_dir%/vendor/batch-jobs/batch-jobs-bundle/templates': batchJobs
        '%kernel.project_dir%/templates': sylius
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    Twig\Extra\Intl\IntlExtension: ~
